#!/usr/bin/env python3
"""Bucket 9 final-audit orchestrator (Part G, item 52).

Runs the cheap, deterministic final checks only — NO model experiments:
  1. LaTeX reference audit        (scripts/audit_latex_references.py)
  2. Manuscript numerical audit   (scripts/audit_manuscript_numbers.py)
  3. Split validation             (scripts/validate_splits.py, if present)
  4. Artifact-existence check     (key result files referenced by the paper)

Writes results/final_audit/latex_final_audit.{json,md} and prints a summary.
Exit code = number of BLOCKING conditions detected (0 == clean).

Usage: python scripts/run_final_audits.py [--repo .]
"""
import argparse, json, os, subprocess, sys

KEY_ARTIFACTS = [
    "results/splits/subject_disjoint_v1.json",
    "results/splits/subject_disjoint_v1_metadata.json",
    "results/tau_rec_sensitivity/filter_sweep_all_models.csv",
    "results/iti_paired/paired_significance.json",
    "results/detector_splitclean/summary.json",
    "results/layer_localization_splitclean/localization_statistics.json",
    "results/variant_ablation",
    "results/baselines",
    "results/benchmark_audit/audit_metadata.json",
    "TAS_AAAI27_submission/main.tex",
    "TAS_AAAI27_submission/supplement.tex",
    "TAS_AAAI27_submission/ref.bib",
]

def run(cmd, repo):
    try:
        p = subprocess.run(cmd, cwd=repo, capture_output=True, text=True, timeout=600)
        return p.returncode, p.stdout + p.stderr
    except Exception as e:
        return 1, f"ERROR running {' '.join(cmd)}: {e}"

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
    args = ap.parse_args()
    repo = os.path.abspath(args.repo)
    outdir = os.path.join(repo, "results/final_audit"); os.makedirs(outdir, exist_ok=True)
    blockers = 0
    report = {"steps": {}}

    # 1. LaTeX ref audit
    rc, out = run([sys.executable, "scripts/audit_latex_references.py"], repo)
    clean = "CLEAN: True" in out
    report["steps"]["latex_reference_audit"] = {"clean": clean, "returncode": rc}
    if not clean: blockers += 1
    with open(os.path.join(outdir, "latex_final_audit.md"), "w") as f:
        f.write("# LaTeX Final Audit\n\n(auto-generated by run_final_audits.py)\n\n```\n" + out + "\n```\n")

    # 2. numerical audit
    rc, out = run([sys.executable, "scripts/audit_manuscript_numbers.py", "--repo", "."], repo)
    stale_clean = "Stale markers: 0" in out
    miss_clean = "0 MISSING" in out
    report["steps"]["numerical_audit"] = {"stale_clean": stale_clean, "no_missing": miss_clean, "log": out.strip().splitlines()[-6:]}
    if not (stale_clean and miss_clean): blockers += 1

    # 3. split validation (optional)
    if os.path.exists(os.path.join(repo, "scripts/validate_splits.py")):
        rc, out = run([sys.executable, "scripts/validate_splits.py"], repo)
        env_issue = "ModuleNotFoundError" in out or "ImportError" in out
        status = "skipped: package not installed (run `pip install -e .`)" if env_issue else ("ok" if rc == 0 else "FAILED")
        report["steps"]["split_validation"] = {"returncode": rc, "status": status, "tail": out.strip().splitlines()[-3:]}
        if rc != 0 and not env_issue: blockers += 1

    # 4. artifact existence
    missing = [p for p in KEY_ARTIFACTS if not os.path.exists(os.path.join(repo, p))]
    report["steps"]["artifact_existence"] = {"missing": missing}
    if missing: blockers += 1

    # 5. benchmark manual-audit status (informational blocker if brackets present)
    main = open(os.path.join(repo, "TAS_AAAI27_submission/main.tex")).read()
    supp = open(os.path.join(repo, "TAS_AAAI27_submission/supplement.tex")).read()
    import re
    bracket = bool(re.search(r"\[\$?[NX]\$?\\?%?\]", main + supp))
    report["steps"]["placeholder_brackets"] = {"present": bracket}
    if bracket: blockers += 1

    report["blockers"] = blockers
    with open(os.path.join(outdir, "latex_final_audit.json"), "w") as f:
        json.dump(report, f, indent=2)

    print(json.dumps(report, indent=2))
    print("\nBLOCKERS:", blockers, "(0 == source-level clean; Overleaf compile still required)")
    sys.exit(blockers)

if __name__ == "__main__":
    main()
